baseURL = "https://irfanykywz.github.io/"
languageCode = "en-us"
title = "irfanykywz"
theme = "hugo-ykywz"

copyright = "irfanykywz"

pagination.pagerSize = 5

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
	# browser icon
	# favicon = "https://avatars.githubusercontent.com/u/117440754?v=4"
  favicon = "avatar.jpg"

	# Optional 64x64 avatar image.
	# avatar = "https://avatars.githubusercontent.com/u/117440754?v=4"
  avatar = "avatar.jpg"

  description = "Website Muhamad Irfan: Memiliki skill dibidang IT Support dan Software Engineering. siap direkrut kapan saja, segera hubungi saya"
  author = "Muhamad Irfan"
  keywords = "Software Engineer, IT Support, Portofolio, Coding, Troubleshooting, Infrastruktur."

# Menu Header
[[menu.main]]
name = "Beranda"
url = "/"
pre = "fas fa-home"
weight = 1

[[menu.main]]
name = "Proyek"
url = "/portofolio/"
pre = "fas fa-briefcase"
weight = 2

# [[menu.main]]
# name = "Learn"
# url = "/learn/"
# pre = "fas fa-graduation-cap"
# weight = 3

[[menu.main]]
name = "Artikel"
url = "/posts/"
pre = "fas fa-blog"
weight = 4

[[menu.main]]
name = "Kontak"
url = "/contact/"
pre = "fas fa-envelope"
weight = 5

# Menu Footer
[[menu.footer]]
name = "Jurnal"
url = "/journal/"
pre = "📝"
weight = 1

[[menu.footer]]
name = "Belajar"
url = "/learn/"
pre = "💡"
weight = 2

[[menu.footer]]
name = "Buku"
url = "/book-lesson/"
pre = "📖"
weight = 2

# Menu Footer Right
[[menu.footer_right]]
name = "🔍"
url = "/search/"
weight = 1

# [[menu.footer_right]]
# name = "#️⃣"
# url = "/tags/"
# weight = 2

# [[menu.footer_right]]
# name = "🏷️"
# url = "/categories/"
# weight = 3

# [[menu.footer_right]]
# name = "📦"
# url = "/collection/"
# weight = 4

[[menu.footer_right]]
name = "🧪"
url = "/research/"
weight = 5

[[menu.footer_right]]
name = "🎮"
url = "/game-journey/"
weight = 6

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "dracula"  # or any other chroma style
    tabWidth = 4

[taxonomies]
  category = 'categories'
  tag = 'tags'

# allow html to content .md
[markup.goldmark.renderer] 
	unsafe= true

# allow shortcodes
[security]
	enableInlineShortcodes = true	

# output format
[outputs]
  home = ["HTML", "RSS", "JSON"]  

[outputFormats]
[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true
  notAlternative = true  

[languages.id]
languageName = "Indonesian"
languageCode = "id"